language: node_js
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - sudo apt-get install -y curl
before_script:
  - docker-compose -f test/docker-compose.yml up --build -d 
script:
  - test/test.sh