language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - SERVER_PORT=3000

jobs:
  include:
    - stage: tests
      script:
        - npm run lint
        - npm run test:unit
        - bash scripts/test-docker-image.sh

stages:
  - name: tests 
    if: type IN (pull_request, push) AND tag IS blank
