version: '3.7'

services:
  basecamp-github-chatbot:
    image: foundersclubsoftware/basecamp-github-chatbot:0.2.0

    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/lib/app/data/
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'