version: '3.7'

services:
  app:
    image: chatbot-app:prod
    build:
      context: ..
      dockerfile: docker/Dockerfile-app.prod
    container_name: chatbot-app-prod

    environment:
      - NODE_ENV=production